### ISSUE TITLE
[BP] XmlParsers, create more classes what load by file or by string

### ISSUE THREAD

**Issue by netzulo** [netzulo/qatestlink#3]
This looks like it should be three classes:

* One with base, common functionality.
* One that accepts `xml_path`.
* One that accepts `xml_str`.

This way you will have better separation of concerns and probably a cleaner code with much less `if`s.

**Comment by Terseus** [comment]
Mmm, I'll try to take it the next week, is the testing Testlink installation public? To write unit tests.
